### ISSUE TITLE
Add image credits on front page

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/tor-councilmatic#19]

**Comment by patcon** [comment]
https://www.flickr.com/photos/thomashawk/11678450124/sizes/l/

**Comment by patcon** [comment]
https://www.flickr.com/photos/57156785@N02/10631429553/sizes/l

**Comment by patcon** [comment]
Done for now in 2eada1191b1441d66199679e187cf3249288f213

**Comment by patcon** [comment]
Re-opening because we need to add attribution for the images :)

**Comment by alexaca79** [comment]
![dscf4284](https://cloud.githubusercontent.com/assets/6887930/15694590/143f8d8e-276d-11e6-8333-58283ca2c494.jpg)
