### ISSUE TITLE
Create icon for Toronto

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/tor-councilmatic#36]
NYC and Chicago have a symbol for their sites (the statue of liberty crown and a star, respectively).

![NYC iconography](https://imgur.com/FDAZQHr.png)

We should decide on a Toronto-centric one.

**Comment by patcon** [comment]
Toronto's best icon is the CN Tower, but it's abit too vertical for the place of the other city's icons.

Entries in the noun project directory don't seem to capture us either:
https://thenounproject.com/search/?q=toronto&i=345494

Perhaps we could adapt one from this:
![CN Tower from below](http://media-2.web.britannica.com/eb-media/62/85162-004-98969BFC.jpg)

**Comment by patcon** [comment]
Not a big fan of it, but here's Toronto's flag:
![toronto flag graphic](https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Toronto_Flag.svg/2400px-Toronto_Flag.svg.png)

It might be the most official form we have. The flag is where chicago's icon comes from, but it seems to be more prominent in the city

**Comment by patcon** [comment]
I wish we could bring back the Metro Toronto logo... SO ELEGANT :)
https://en.wikipedia.org/wiki/Metropolitan_Toronto

**Comment by shaqsingh** [comment]
meep forgot to upload this. Want me to do a metro toronto one? wouldnt be too difficult. it's not very recognizable though
![to-01](https://cloud.githubusercontent.com/assets/3852724/16064674/4a34988a-3271-11e6-8668-f3b73b8f4023.png)

**Comment by patcon** [comment]
nice! thanks! but no no with the Metro logo -- I just saw it on the walls at city hall last week, and realized we had graphic design glory days :)

Couple small things:
- Thoughts on filling in the council chambers outline? The inconsistent line widths strike me as a little too noticeable, and not sure how that'll fare on resizing.
- it seems that the line along the bottom needs some sub-pixel adjustments, as there's anti-aliasing on the top. Is that something you could tweak?
- Can you render it in a few square sizes, at least down to 16x16 so that it fills the whole canvas (as it would need to for a favicon)?

**Comment by shaqsingh** [comment]
![cityhall-01](https://cloud.githubusercontent.com/assets/3852724/16122988/5180236a-33b7-11e6-9f88-9d341973b686.png)
![cityhall-h30](https://cloud.githubusercontent.com/assets/3852724/16123249/4be12070-33b8-11e6-9292-fe843b1638f8.png)
![cityhall-h50-01](https://cloud.githubusercontent.com/assets/3852724/16123250/4bef0370-33b8-11e6-8ad6-09e3fad35867.png)

**Comment by shaqsingh** [comment]
![cityhall-h16](https://cloud.githubusercontent.com/assets/3852724/16123377/b51f1178-33b8-11e6-970b-c885b26e4a7f.png)

i think this is the right 16x16 file

**Comment by shaqsingh** [comment]
let me know if you need any more tweaks!

**Comment by patcon** [comment]
Thanks! Not sure what 16x16 was in your editor, but I was referring to 16x16 pixels, like for the favicon that shows up in tabs. I think we'd need to make sure that whatever we choose for a logo, it works at that scale. Also, favicons must be square, so we've got to sort that out :)

Maybe we could keep all these iterations in the Councilmatic folder on drive too? A canonical vector graphic (or PSD or whatever) with maximum image data is probably a good idea too? I don't know, I haven't worked with graphic designers in a bit, but I think that's a standard approach to make sure new images at any size are not lossy

**Comment by patcon** [comment]
I just quickly scaled the image down to 16x16, and it's unfortunately pretty unrecognisable. Since the favicon is one of the more important uses of the icon, I think we've got to sort that out before we can lock in the design. You up for making that work?

EDIT: Also, interested in feedback on the "nest". It's not quite looking right filled in either. I'm not sure, what do you think? Maybe if the lines were all the same, it might be a little less distracting?

**Comment by shaqsingh** [comment]
![ch-01](https://cloud.githubusercontent.com/assets/3852724/16134002/df3f2878-33e8-11e6-8129-b11c205fa1dc.png)
ppi was off sry

**Comment by shaqsingh** [comment]
my bad!  I could do a different version, but the one I just sent is more legible than the one on toronto.ca imo

**Comment by shaqsingh** [comment]
oh and here is one with no filled in nest. could also do a completely different one with a more abstract one?
![cc-01](https://cloud.githubusercontent.com/assets/3852724/16134258/3233cc54-33ea-11e6-87d7-2e917cd98de7.png)

**Comment by shaqsingh** [comment]
Also, re: Councilmatic folder on drive I don't think I have access to it? I can absolutely provide the illustrator file though

**Comment by patcon** [comment]
Wow! that looks tons better! I should've known scaling down a PNG would be incomparable :)

And just gave you access to the Councilmatic gdrive dir, if you want to drop those assets somewhere. Thanks!
