### ISSUE TITLE
Update councillor dataset

### ISSUE THREAD

**Issue by patcon** [CivicTechTO/tor-councilmatic#68]
Ward 2 councillor is still vacant: http://councilmatic.t0ronto.ca/council-members/

I'll create a temporary gist for now, to pull from.

Sent this email to City of Toronto's Open Data team:

> Hey folks,
> 
> My scrapers are getting out-of-date info from this dataset. Any chance it could be updated?
> 
> http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=404a1f4e3159c410VgnVCM10000071d60f89RCRD&vgnextchannel=1a66e03bb8d1e310VgnVCM10000071d60f89RCRD
> 
> Also, would you consider adding columns for start and end dates, and then the same dataset could be used indefinitely as a consistent data source for all past/future councillors?
> 
> Thanks!

@jpmckinney I know that the general CSV format is something you quasi-standardized. Has anyone added start/end date columns that we can keep things consistent with?

**Comment by patcon** [comment]
Addressed in https://github.com/tor-councilmatic/scrapers-ca/commit/73daf1df67a15b3a363f8163f6380a83495380e9

Will leave open until Open Data team addresses canonically

**Comment by jpmckinney** [comment]
Governments are really bad at maintaining historical data, unless the history is important (e.g. contracts awarded). Old lists of councillors are not important, so it'd require a fair bit of convincing to make them add start/end date columns.

**Comment by patcon** [comment]
Open Data team forwarded the request for start/end dates to [Election Services](http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=4ff1a5977effd310VgnVCM1000006cd60f89RCRD). Waiting to hear back
